### ISSUE TITLE
Handle error/stack trace when LDAP server is down

### ISSUE THREAD

**Issue by StigLau** [altran/_Whydah-UserIdentityBackend#15]
06:51:45.189 [Grizzly(1)] DEBUG n.w.i.u.i.LdapAuthenticatorImpl - Trying to authenticate with username and password. username=erikd
06:51:45.223 [Grizzly(1)] DEBUG n.w.i.u.i.LdapAuthenticatorImpl - Found userDN=uid=erik.drolshammer,ou=users,dc=external,dc=WHYDAH,dc=no
06:51:45.257 [Grizzly(1)] DEBUG n.w.i.u.i.LdapAuthenticatorImpl - Authentication failed for user erikd
javax.naming.AuthenticationException: [LDAP: error code 49 - INVALID_CREDENTIALS: Bind failed: ERR_229 Cannot authenticate user uid=erik.drolshammer,ou=users,dc=external,dc=WHYDAH,dc=no]
	at net.whydah.identity.user.identity.LdapAuthenticatorImpl.authenticate(LdapAuthenticatorImpl.java:69) ~[UserIdentityBackend-2.0-SNAPSHOT.jar:na]
	at net.whydah.identity.user.identity.UserIdentityService.authenticate(UserIdentityService.java:62) [UserIdentityBackend-2.0-SNAPSHOT.jar:na]
	at net.whydah.identity.user.authentication.UserAuthenticationEndpoint.authenticateUser(UserAuthenticationEndpoint.java:118) [UserIdentityBackend-2.0-SNAPSHOT.jar:na]
	at net.whydah.identity.user.authentication.UserAuthenticationEndpoint.authenticateUser(UserAuthenticationEndpoint.java:114) [UserIdentityBackend-2.0-SNAPSHOT.jar:na]
06:51:45.258 [Grizzly(1)] TRACE n.w.i.u.a.UserAuthenticationEndpoint - Authentication failed for user with username=erikd. Returning Forbidden

**Comment by sherriff** [comment]
moved
