### ISSUE TITLE
UIB does not reconnect connection to LDAP when the connection breaks

### ISSUE THREAD

**Issue by StigLau** [altran/_Whydah-UserIdentityBackend#45]
Adding user in UserAdminWebApp throws LDAP related exception: usernameExist failed for username= 

13:15:41.846 [Grizzly(1)] TRACE n.w.identity.security.SecurityFilter - filter path /1f0e3dad99908345f7439f8ffabdffc4/447c5120-ecb4-49e8-a751-2f4448cc4bb8/user/
13:15:41.846 [Grizzly(1)] DEBUG n.w.identity.security.SecurityFilter - usertokenid: 447c5120-ecb4-49e8-a751-2f4448cc4bb8 from path=/1f0e3dad99908345f7439f8ffabdffc4/447c5120-ecb4-4
9e8-a751-2f4448cc4bb8/user/
13:15:41.846 [Grizzly(1)] TRACE n.w.identity.security.SecurityFilter - ApplicationMode -PROD-
13:15:41.846 [Grizzly(1)] DEBUG n.w.i.u.a.SecurityTokenServiceHelper - usertokenid=447c5120-ecb4-49e8-a751-2f4448cc4bb8
13:15:41.883 [Grizzly(1)] INFO  n.w.i.u.a.SecurityTokenServiceHelper - Accessing:tokenservice/1f0e3dad99908345f7439f8ffabdffc4/get_usertoken_by_usertokenid
13:15:41.883 [Grizzly(1)] DEBUG n.w.i.u.a.SecurityTokenServiceHelper - usertoken: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<usertoken xmlns:ns2="http://www.w3.org/1999/xhtml" id="447c5120-ecb4-49e8-a751-2f4448cc4bb8">
    <uid>admin</uid>
    <timestamp>1415365032672</timestamp>
    <lifespan>3600000</lifespan>
    <issuer></issuer>
    <securitylevel>1</securitylevel>
    <DEFCON>5</DEFCON>
    <username>admin</username>
    <firstname>Admin</firstname>
    <lastname>Admin</lastname>
    <email>admin@getwhydah.com</email>
    <personRef>0</personRef>
    <application ID="19">
        <applicationName>UserAdminWebApp</applicationName>
        <organizationName>Support</organizationName>
        <role name="WhydahUserAdmin" value="1"/>
    </application>

    <ns2:link type="application/xml" href="/447c5120-ecb4-49e8-a751-2f4448cc4bb8" rel="self"/>
    <hash type="MD5">f70045a25cd51ed77247739ed0591911</hash>
</usertoken>

13:15:41.887 [Grizzly(1)] DEBUG n.w.identity.security.SecurityFilter - setAuthenticatedUser with usertoken: UserToken{name='Admin Admin', userRoles=[UserRole{appId='19', orgName='S
upport', roleName='WhydahUserAdmin'}]}
13:15:41.887 [Grizzly(1)] INFO  n.w.i.user.resource.UserResource - Started: UserResource
upport', roleName='WhydahUserAdmin'}]}
13:15:41.887 [Grizzly(1)] INFO  n.w.i.user.resource.UserResource - Started: UserResource
13:15:41.888 [Grizzly(1)] TRACE n.w.i.user.resource.UserResource - addUserIdentity, userIdentityJson={"username":"bjartebjart","firstName":"bjarte","lastName":"bjart","email":"bjart@bjart.no","cellPhone":"1234","personRef":"yes"}
13:15:41.889 [Grizzly(1)] TRACE n.w.i.u.identity.LdapUserIdentityDao - Search for user using: initials=bjartebjart
13:15:41.889 [Grizzly(1)] TRACE n.w.i.u.identity.LdapUserIdentityDao - NamingException. usernameAttribute initials, username bjartebjart
13:15:41.890 [Grizzly(1)] ERROR n.w.i.user.resource.UserResource - addUserIdentity-RuntimeExeption
java.lang.RuntimeException: usernameExist failed for username=bjartebjart
        at net.whydah.identity.user.identity.UserIdentityService.addUserIdentityWithGeneratedPassword(UserIdentityService.java:124) ~[UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at net.whydah.identity.user.resource.UserResource.addUserIdentity(UserResource.java:78) ~[UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:187) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:71) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:280) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1341) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1273) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1223) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1213) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.servlet.ServletHandler$FilterChainImpl.doFilter(ServletHandler.java:975) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at net.whydah.identity.security.SecurityFilter.doFilter(SecurityFilter.java:110) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.servlet.ServletHandler$FilterChainImpl.doFilter(ServletHandler.java:959) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.google.inject.servlet.DefaultFilterPipeline.dispatch(DefaultFilterPipeline.java:43) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.servlet.ServletHandler$FilterChainImpl.doFilter(ServletHandler.java:959) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.servlet.ServletHandler$FilterChainImpl.invokeFilterChain(ServletHandler.java:914) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:374) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:322) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:162) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.http.server.HttpHandlerChain.service(HttpHandlerChain.java:195) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:162) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:160) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.filterchain.ExecutorResolver$3.execute(ExecutorResolver.java:95) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:444) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:364) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:290) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:133) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:76) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:63) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:823) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:113) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:116) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$000(WorkerThreadIOStrategy.java:55) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$1.run(WorkerThreadIOStrategy.java:98) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:508) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:488) [UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: javax.naming.CommunicationException: Connection timed out
        at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:2003) ~[na:1.7.0_71]
        at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1847) ~[na:1.7.0_71]
        at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1772) ~[na:1.7.0_71]
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:386) ~[na:1.7.0_71]
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:356) ~[na:1.7.0_71]
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:339) ~[na:1.7.0_71]
        at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267) ~[na:1.7.0_71]
        at net.whydah.identity.user.identity.LdapUserIdentityDao.getUserAttributesForUsername(LdapUserIdentityDao.java:307) ~[UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at net.whydah.identity.user.identity.LdapUserIdentityDao.getUserAttributesForUsernameOrUid(LdapUserIdentityDao.java:267) ~[UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at net.whydah.identity.user.identity.LdapUserIdentityDao.getUserIndentity(LdapUserIdentityDao.java:224) ~[UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at net.whydah.identity.user.identity.LdapUserIdentityDao.usernameExist(LdapUserIdentityDao.java:262) ~[UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        at net.whydah.identity.user.identity.UserIdentityService.addUserIdentityWithGeneratedPassword(UserIdentityService.java:119) ~[UserIdentityBackend-2.0.20-20141026.100758-8.jar:na]
        ... 47 common frames omitted
Caused by: java.net.SocketException: Connection timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.7.0_71]
        at java.net.SocketInputStream.read(SocketInputStream.java:152) ~[na:1.7.0_71]
        at java.net.SocketInputStream.read(SocketInputStream.java:122) ~[na:1.7.0_71]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235) ~[na:1.7.0_71]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:275) ~[na:1.7.0_71]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334) ~[na:1.7.0_71]
        at com.sun.jndi.ldap.Connection.run(Connection.java:853) ~[na:1.7.0_71]
        ... 1 common frames omitted

**Comment by sherriff** [comment]
moved
